import type { SkinDefinition } from "./tokens";

export const bootstrap: SkinDefinition = {
  tokens: {
    font: "system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    fontSize: 16,
    headingWeight: 500,
    text: "#212529",
    textMuted: "#6c757d",
    bg: "#ffffff",
    surface: "#ffffff",
    mutedBg: "#f8f9fa",
    border: "#dee2e6",
    primary: "#0d6efd",
    primaryFg: "#ffffff",
    secondary: "#6c757d",
    secondaryFg: "#ffffff",
    neutral: "#f8f9fa",
    neutralFg: "#212529",
    danger: "#dc3545",
    success: "#198754",
    warning: "#ffc107",
    info: "#0dcaf0",
    radius: 6,
    radiusLg: 8,
    shadow1: "0 .125rem .25rem rgba(0,0,0,.075)",
    shadow2: "0 .5rem 1rem rgba(0,0,0,.15)",
    shadow3: "0 1rem 3rem rgba(0,0,0,.175)",
    controlH: 38,
    controlHSm: 31,
    controlHLg: 48,
    borderWidth: 1,
    focusRing: "0 0 0 .25rem rgba(13, 110, 253, .25)",
  },
  vars: {
    buttonTransform: "none",
    buttonWeight: 400,
    buttonLetterSpacing: "0",
    buttonShadow: "none",
    cardShadow: "none",
    inputBg: "#ffffff",
    badgeRadius: "6px",
    tableHeadBg: "transparent",
    navbarBg: "var(--pf-surface)",
    navbarFg: "var(--pf-text)",
  },
  structure: { inputLabel: "above", tabs: "pills", switch: "inset" },
};
