import type { SkinDefinition } from "./tokens";

export const wireframe: SkinDefinition = {
  tokens: {
    font: "var(--font-geist-sans), system-ui, sans-serif",
    fontSize: 14,
    headingWeight: 700,
    text: "#222222",
    textMuted: "#7a7a7a",
    bg: "#ffffff",
    surface: "#ffffff",
    mutedBg: "#ececec",
    border: "#3a3a3a",
    primary: "#3a3a3a",
    primaryFg: "#ffffff",
    secondary: "#8a8a8a",
    secondaryFg: "#ffffff",
    neutral: "#d4d4d4",
    neutralFg: "#222222",
    danger: "#555555",
    success: "#6a6a6a",
    warning: "#9a9a9a",
    info: "#7a7a7a",
    radius: 4,
    radiusLg: 6,
    shadow1: "none",
    shadow2: "none",
    shadow3: "none",
    controlH: 36,
    controlHSm: 28,
    controlHLg: 44,
    borderWidth: 1.5,
    focusRing: "none",
  },
  vars: {
    buttonTransform: "none",
    buttonWeight: 600,
    buttonLetterSpacing: "0",
    buttonShadow: "none",
    cardShadow: "none",
    inputBg: "#ffffff",
    badgeRadius: "999px",
    tableHeadBg: "#ececec",
    navbarBg: "var(--pf-surface)",
    navbarFg: "var(--pf-text)",
  },
  structure: { inputLabel: "above", tabs: "underline", switch: "inset" },
};
