import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = process.cwd();
const dir = path.join(root, "exporter-check", "fidelity");
const out = path.join(dir, ".out");
const thresholds = JSON.parse(readFileSync(path.join(dir, "thresholds.json"), "utf8"));
const KIT_RULES = new Set(["color-contrast"]);

const results = readdirSync(out)
  .filter((f) => f.endsWith(".json"))
  .map((f) => JSON.parse(readFileSync(path.join(out, f), "utf8")));

const targets = [...new Set(results.map((r) => r.target))].sort();
const templates = [...new Set(results.map((r) => r.template))].sort();
const cell = (t, tpl) => results.find((r) => r.target === t && r.template === tpl);

const lines = [
  "# Export fidelity",
  "",
  "How close the exported code looks to the editor. For every target and starter template, the exported screen is rendered with the real UI library and compared with the editor's screenshot of the same artboard in that skin. The number is the share of differing pixels among pixels that carry content (not background) in either image. Lower is better.",
  "",
  "Generated by `pnpm fidelity` (see `exporter-check/README.md`). CI fails when a cell goes above the threshold for its target or when the export has an accessibility violation that the exporter controls.",
  "",
  `| Target | ${templates.join(" | ")} | Threshold |`,
  `|---|${templates.map(() => "---:").join("|")}|---:|`,
  ...targets.map(
    (t) =>
      `| ${t} | ${templates.map((tpl) => `${cell(t, tpl)?.diffPct ?? "-"}%`).join(" | ")} | ${thresholds[t]}% |`,
  ),
  "",
  "## Accessibility",
  "",
  "axe-core runs on every rendered export. Serious and critical violations:",
  "",
];

const fails = [];
for (const r of results) {
  if (r.diffPct > thresholds[r.target])
    fails.push(`${r.target} ${r.template}: ${r.diffPct}% > ${thresholds[r.target]}%`);
  for (const v of r.axe)
    if (!KIT_RULES.has(v.id)) fails.push(`${r.target} ${r.template}: axe ${v.id}`);
}
const kit = results
  .filter((r) => r.axe.some((v) => KIT_RULES.has(v.id)))
  .map((r) => `${r.target} ${r.template}`);
const own = results.flatMap((r) =>
  r.axe.filter((v) => !KIT_RULES.has(v.id)).map((v) => `${r.target} ${r.template}: ${v.id}`),
);
lines.push(own.length ? own.map((o) => `- ${o}`).join("\n") : "- None that the exporter controls.");
lines.push(
  "",
  `Color contrast findings come from the libraries' default palettes (secondary and muted text), not from the exported structure: ${kit.length} of ${results.length} screens.`,
  "",
);

writeFileSync(path.join(root, "docs", "FIDELITY.md"), lines.join("\n"));
console.log(lines.slice(6, 8 + targets.length).join("\n"));
if (fails.length) {
  console.error(`\nFidelity check failed:\n${fails.map((f) => `  ${f}`).join("\n")}`);
  process.exit(1);
}
console.log("\nFidelity check passed. Wrote docs/FIDELITY.md.");
